        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*LEMBRETES:
1 - fazer uma função 'adicionarnaTabela'
*/
package br.com.ifba.curso.view;

import br.com.ifba.curso.dao.dao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.util.Verificador;
import br.com.ifba.curso.util.Output;

/**
 *
 * @author Casa
 */
public class CursoListar extends javax.swing.JFrame {

    final DefaultTableModel tableModel;
    boolean pesquisaFeita = false;
    int itemSelecionado = -1; // como não consegui fazer a criaçao de botões de maneira dinâmica o user seleciona e a partir disso faz as escolhas 
    List<Curso> listaCursos = new ArrayList();
    Verificador verificar = new Verificador();

   final dao dao = new dao();//instanciando para a integração com o BD

    public CursoListar() {
        initComponents();
        // modelo da tabela
        tableModel = (DefaultTableModel) tblCursos.getModel();
        jOptionPane1.setVisible(false);

        carregarDados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrameADDcurso = new javax.swing.JFrame();
        txtnomeNovo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        cbnovoStatus = new javax.swing.JComboBox<>();
        txtnovoCodigo = new javax.swing.JTextField();
        txtnovosAlunos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFrameEditar = new javax.swing.JFrame();
        txteditarNome = new javax.swing.JTextField();
        txteditarAlunos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnsalvarAlteracoes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbEditar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btndesfazerPesquisa = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        btnPesquisar = new javax.swing.JButton();

        JFrameADDcurso.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JFrameADDcurso.getContentPane().add(txtnomeNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Alunos matriculados");
        JFrameADDcurso.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Código");
        JFrameADDcurso.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Status");
        JFrameADDcurso.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmar.setText("Enviar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        JFrameADDcurso.getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 80, 40));

        cbnovoStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Desativado" }));
        JFrameADDcurso.getContentPane().add(cbnovoStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        JFrameADDcurso.getContentPane().add(txtnovoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 310, 34));

        txtnovosAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnovosAlunosActionPerformed(evt);
            }
        });
        JFrameADDcurso.getContentPane().add(txtnovosAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nome do curso");
        JFrameADDcurso.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jFrameEditar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jFrameEditar.getContentPane().add(txteditarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 49, 335, 44));

        txteditarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteditarAlunosActionPerformed(evt);
            }
        });
        jFrameEditar.getContentPane().add(txteditarAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 157, 335, 44));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Novo nome");
        jFrameEditar.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 6, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Novo Status do Curso");
        jFrameEditar.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnsalvarAlteracoes.setText("Salvar");
        btnsalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarAlteracoesActionPerformed(evt);
            }
        });
        jFrameEditar.getContentPane().add(btnsalvarAlteracoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nova quantidade de alunos");
        jFrameEditar.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 126, -1, -1));

        cbEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Desativado" }));
        cbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditarActionPerformed(evt);
            }
        });
        jFrameEditar.getContentPane().add(cbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código do curso", "Status", "Alunos matriculados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.setFillsViewportHeight(true);
        tblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 490, -1));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/image-removebg-preview (2).png"))); // NOI18N
        btnAdicionar.setPreferredSize(new java.awt.Dimension(70, 70));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 55, 43));

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 440, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/image-removebg-preview (1).png"))); // NOI18N
        btnEditar.setPreferredSize(new java.awt.Dimension(70, 70));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 55, 43));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/image-removebg-preview.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 55, 43));

        btndesfazerPesquisa.setText("Desfazer pesquisa");
        btndesfazerPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesfazerPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btndesfazerPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jOptionPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOptionPane1MouseClicked(evt);
            }
        });
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/image-removebg-preview (3) (1).png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 55, 43));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarDados() {

        tableModel.setRowCount(0);
        listaCursos.clear();

        List<Curso> listaCapsula = dao.findAll();//passnado todos os itens do BD  para a lista

        for (Curso curso : listaCapsula) {
            listaCursos.add(curso); //passando todos os itens da lista capsula para a lista local
            tableModel.addRow(new Object[]{
                curso.getNome(),
                curso.getCodigoCurso(),
                formatarStatus(curso.getAtivo()),
                curso.getAlunosMatriculados()
            });
        }

    }

    public void adicionarCurso(Curso curso) {
        
       if( verificar.objetoNulo(curso) == true){
       return;
       }

        Curso novoCurso = new Curso(curso.getNome(), curso.getCodigoCurso(), curso.getAtivo(),curso.getAlunosMatriculados());//encapsulamento via objeto

        listaCursos.add(novoCurso);//adicionar curso na lista

        tableModel.addRow(new Object[]{
            novoCurso.getNome(), novoCurso.getCodigoCurso(), formatarStatus(novoCurso.getAtivo()),novoCurso.getAlunosMatriculados()});//adicionar curso na Jtable

        dao.save(curso);//adiciona o curso no banco de dados

    }

    public void editarCurso(Curso cursoEditado) {

        tblCursos.setValueAt(cursoEditado.getNome(), itemSelecionado, 0);//atualizar     
        tblCursos.setValueAt(cursoEditado.getCodigoCurso(), itemSelecionado, 1);// a
        tblCursos.setValueAt(formatarStatus(cursoEditado.getAtivo()), itemSelecionado,2);// tabela
        tblCursos.setValueAt(cursoEditado.getAlunosMatriculados(), itemSelecionado, 3);
        
        listaCursos.set(itemSelecionado, cursoEditado);//atualizo a lista

        dao.update(cursoEditado);//atualizo no  BD

    }

    public void resetarSeleçao() {
        itemSelecionado = -1;// 'deselecionar' toda vez que encerrar uma ação
    }

    public void limparcaixadeTexto() {

        txtnomeNovo.setText("");//limapando as...
        txtnovosAlunos.setText("");// ...caixas de texto
        txtnovoCodigo.setText("");
        txteditarAlunos.setText("");
    }

    public boolean verificarStatusComboBox(javax.swing.JComboBox<String> comboBox){//refatorei as duas funções em apenas uma
    
    String selecao = (String) comboBox.getSelectedItem();

        if (selecao.equals("Ativo")) {

            return true;
        } else {

            return false;
        }
        
    }
    
    //para não ficar aparecendo na tabela 'true' ou 'false'
    public String formatarStatus(boolean status) {

        if (status) {

            return "Ativo";
        } else {
            return "Desativado";
        }

    }

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        JFrameADDcurso.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

  Curso capsulaCurso = new Curso(txtnomeNovo.getText(), Long.parseLong(txtnovoCodigo.getText()), verificarStatusComboBox(cbnovoStatus),Integer.parseInt(txtnovosAlunos.getText()));//criando um obleto para passar os parametros tanto na lsita qunato na tabela

        for (Curso curso : listaCursos) {

            if (curso.getCodigoCurso() == capsulaCurso.getCodigoCurso()) {//verificar incidencia de repetições

                jOptionPane1.showMessageDialog(null, "Código já existente, não foi possível adicionar o novo curso");

                return;
            }

        }

        adicionarCurso(capsulaCurso);

        limparcaixadeTexto();

        JFrameADDcurso.setVisible(false);

        resetarSeleçao();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (listaCursos.isEmpty()) {

            jOptionPane1.showMessageDialog(null, "Nenhum curso cadastrado");

            return;
        }

        if (itemSelecionado == -1) {
            
            jOptionPane1.showMessageDialog(null, "Nenhum curso Selecionado");

            return;
        }

        jFrameEditar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (listaCursos.isEmpty()) {//verificar existencia de itens na lista

            jOptionPane1.showMessageDialog(null, "Nenhum curso cadastrado");

            return;
        }

        if (itemSelecionado == -1) {//ver se o user selecionou algo

            jOptionPane1.showMessageDialog(null, "Nenhum curso Selecionado");

            return;
        }

        Curso cursoExcluir = listaCursos.get(itemSelecionado);

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir o curso:\n" + cursoExcluir.getNome() + "?",
                "Confirmação de exclusão",
                JOptionPane.YES_NO_OPTION
        );
                        //0 = sim | 1 = não | -1 = nada
        if (resposta == JOptionPane.YES_OPTION) {
            listaCursos.remove(itemSelecionado);
            tableModel.removeRow(itemSelecionado);
            dao.delete(cursoExcluir);

            resetarSeleçao();
        }

        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnsalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarAlteracoesActionPerformed

       if (listaCursos.isEmpty()) {
    jOptionPane1.showMessageDialog(null, "Nenhum curso cadastrado");
    return;
}

if (itemSelecionado == -1) {
    jOptionPane1.showMessageDialog(null, "Nenhum curso Selecionado");
    return;
}

Curso cursoSelecionado = listaCursos.get(itemSelecionado);

if (txteditarNome.getText().isEmpty()) {//estando o espaçao vazio manter inalterado
    cursoSelecionado.setNome(txteditarNome.getText());
}

if (txteditarAlunos.getText().isEmpty()) {
    
    txteditarAlunos.setText(Integer.toString(cursoSelecionado.getAlunosMatriculados()));
      
}

cursoSelecionado.setAtivo(verificarStatusComboBox(cbEditar));

        editarCurso(cursoSelecionado);//atualizar tanto a tabela como o bd e a lisyta

        limparcaixadeTexto();
        
        jFrameEditar.setVisible(false);
        
    }//GEN-LAST:event_btnsalvarAlteracoesActionPerformed

    private void btndesfazerPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesfazerPesquisaActionPerformed

        if (listaCursos.isEmpty()) {
            jOptionPane1.showMessageDialog(null, "Nenhum curso cadastrado");
            return;
        }

        tableModel.setRowCount(0);//limpar tabela para aparecer os itens pesquisados

        for (Curso curso : listaCursos) {
            tableModel.addRow(new Object[]{
                curso.getNome(),
                curso.getCodigoCurso(),
                formatarStatus(curso.getAtivo()),
                curso.getAlunosMatriculados()
            });
        }//preencher a tabela com os itens correspondentes

        pesquisaFeita = false;
        txtPesquisa.setText("");
    }//GEN-LAST:event_btndesfazerPesquisaActionPerformed

    private void tblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursosMouseClicked
        itemSelecionado = tblCursos.getSelectedRow();//para registrar que linha foi selecionada
    }//GEN-LAST:event_tblCursosMouseClicked

    private void jOptionPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOptionPane1MouseClicked


    }//GEN-LAST:event_jOptionPane1MouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        if (txtPesquisa.getText().isEmpty()) {
            jOptionPane1.showMessageDialog(null, "Caixa de pesquisa vazia");
            return;
        }

        String termo = txtPesquisa.getText().trim();
        tableModel.setRowCount(0);

        try {
            //tenta procurar pelo ID
            Long id = Long.parseLong(termo);
            Curso curso = dao.findById(id);

            if (curso != null) {
                tableModel.addRow(new Object[]{
                    curso.getNome(),
                    curso.getCodigoCurso(),
                    formatarStatus(curso.getAtivo())
                });
            } else {
                jOptionPane1.showMessageDialog(null, "Nenhum curso encontrado com esse ID.");
            }
        } catch (NumberFormatException e) {
            //se não for número, pesquisa por nome
            List<Curso> resultados = dao.findByName(termo);

            if (resultados.isEmpty()) {
                jOptionPane1.showMessageDialog(null, "Nenhum curso encontrado com esse nome.");
            } else {
                for (Curso curso : resultados) {
                    tableModel.addRow(new Object[]{
                        curso.getNome(),
                        curso.getCodigoCurso(),
                        formatarStatus(curso.getAtivo()) // Método para formatar status
                    });
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txteditarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteditarAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteditarAlunosActionPerformed

    private void cbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditarActionPerformed

    }//GEN-LAST:event_cbEditarActionPerformed

    private void txtnovosAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnovosAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnovosAlunosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JFrameADDcurso;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btndesfazerPesquisa;
    private javax.swing.JButton btnsalvarAlteracoes;
    private javax.swing.JComboBox<String> cbEditar;
    private javax.swing.JComboBox<String> cbnovoStatus;
    private javax.swing.JFrame jFrameEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txteditarAlunos;
    private javax.swing.JTextField txteditarNome;
    private javax.swing.JTextField txtnomeNovo;
    private javax.swing.JTextField txtnovoCodigo;
    private javax.swing.JTextField txtnovosAlunos;
    // End of variables declaration//GEN-END:variables
}
